### ISSUE TITLE
Support compile_commands.json

### ISSUE THREAD

**Issue by quicknir** [jart/disaster#15]
Disaster looks like a nice tool and the only one of its kind for emacs. However, it seems to only support Make and default compilation. If you are working with a large project that does not use Make which is increasingly common, it seems like there is no way to use it.

compile_commands.json is probably at present the closest thing to a standard way in C++ community to describe the compilation flags for a project. In addition to being used by all of the clang static analyzer tools, it can be generated automatically by both CMake and ninja, as well as from Make using Bear. Furthermore it's the format of choice for other very popular emacs C++ tools like rtags and emacs-ycmd.

Any interest in adding support?

**Comment by jart** [comment]
I would be open to a pull request adding support for this. So long as the old functionality continues to work. I'm sure there are some heuristics we can use to determine which build system the user is using.

**Comment by quicknir** [comment]
I think probably I will fork; I'm not really excited to deal with json in elisp, would rather move most of the current implementation into python and not interested in dealing with makefiles at all there. Will probably aim to have much tighter coupling with my other C++ related code for emacs, e.g. for other packages that also use compile_commands.json such as ycmd.

**Comment by jart** [comment]
If you're adding this support for Emacs then you're going to deal with elisp at some layer of the stack. I'm happy to cooperate with you, review your code, and get a release of this project rolled out to Elpa. I have no qualms with you invoking a Python subprocess in cases where the JSON file is found. The only thing I can't do is write this feature myself, because I don't maintain any software that uses this format.
