### ISSUE TITLE
integration with cmake-ide

### ISSUE THREAD

**Issue by myrgy** [jart/disaster#19]
Hello,

I'm using cmake-ide plugin to build my project.
Is there any way to configure disaster to use compilation commands from cmake-ide and ask cmake-ide to compile files?

**Comment by jart** [comment]
Hey @atilaneves. Our friend @myrgy is a fan of your CMake IDE. He's interested in Disaster support. In case you're wondering, Disaster is a keyboard shortcut that disassembles the current file, and highlights the line of assembly code that corresponds to the C++ code under your cursor. The Spacemacs developers thought highly enough of Disaster to bundle it as a [featured feature](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/c-c%2B%2B) for C/C++ developers.

While I've edited CMake configurations working on TensorFlow, I myself have never run the software, so it's doubtful I could drive such efforts. However, if either of you had the cycles to improve our CMake story, I'd promise you here and now that I would support your efforts. I hope you feel that Disaster is something worth consideration, because there's a chance it could bring much value to your users.

**Comment by atilaneves** [comment]
Ok, what would you need from me?

**Comment by jart** [comment]
@atilaneves Someone wouldn't be able to create a popular IDE without first being at least one standard deviation ahead in terms of creativity and vision. All I would need such a man is that you give Disaster a try. That's all. Because if you do, you might discover that you like it, in which case you would want your users to benefit from the idea. That might involve borrowing the idea and implementing it yourself, copying disaster.el into your codebase, or perhaps sending patches here that would grant it turn-key support with your project. In any case, I would be happy to support your efforts.

**Comment by ageldama** [comment]
@atilaneves https://github.com/ageldama/configs/blob/master/emacs/cmake-ide/cmake-ide.el#L215

**Comment by myrgy** [comment]
hence closed.
